name: Run EasyBuggy Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # This can be adjusted based on your system, e.g., `windows-latest` for Windows runners.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'  # Use Java 1.8 for EasyBuggy

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'

    - name: Install dependencies and run tests
      run: |
        mvn clean install
        mvn test  # Run tests (if applicable)
