name: EasyBuggy Build and Test
 
on:

  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted
 
    steps:
 
    # Build the project with Maven

    - name: Build with Maven

      run: mvn clean install
