name: EasyBuggy Build and Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'

    # Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/settings.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Build the project with Maven
    - name: Build with Maven
      env:
        MAVEN_OPTS: -Xms256m -Xmx512m
      run: mvn clean install -e -X

    # Run tests
    - name: Run tests
      run: mvn test

    # Archive build logs (optional)
    - name: Archive logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: maven-logs
        path: target/surefire-reports
