name: EasyBuggy Build and Test
 
on:

  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted
 
    steps:

    # Checkout the code

    - name: Checkout code

      uses: actions/checkout@v3
 
    # Set up JDK

    - name: Set up JDK 11

      uses: actions/setup-java@v3

      with:

        java-version: 11

        distribution: 'temurin'
 
    # Build the project with Maven

    - name: Build with Maven

      run: mvn clean install
